services:
  server-discovery:
    image: order-management-service:1.0.0
    build:
      dockerfile: Dockerfile
    container_name: server-discovery
    ports:
      - 7070:7070
    restart: unless-stopped
    networks:
      - server-discovery-network
networks:
  server-discovery-network:
    name: order-management-network